### ISSUE TITLE
Smart filter options

### ISSUE THREAD

**Issue by gorjious** [florianpircher/GutenTag#30]
Started using GutenTag as a way of noting what is done, what needs works, things I've checked, etc. Didn't have a clear idea of what tags I would need so I just kept adding as needed. At some point, I wanted to be able to see all the tags I've added to organize further and filter through them. 

I'd like to note a couple of questions, observations, and feature requests:
1. In the Smart Filter list would it be possible to extend the search from Contains to the full dropdown list with Contains, Doesn't Contain, Begins With, Ends With, etc.? This could be helpful if, for example, someone adds a Done tag then wants to filter all the not Done (doesn't contain Done tag) glyphs.

2. The portion in the smart filter option for the name of the tag...would it be possible for that to be a dropdown that is automatically populated by all the available tags? If this is possible would the tags stay hot-linked if tag names are changed later on?

3. On a tangential note, is there a way to see all the tags (to view, organize, rename, access the glyphs within the tag)...if not, would this be useful additional perhaps through a popup window UI or an extension of the tags panel (sort of how the Reporters plugin has the Edit view to see all the list of possible reporter plugins )?

**Comment by florianpircher** [comment]
1: **doesn’t contain:** Create an empty smart filter, hold down the Option key and press the ••• button, then switch to the _None_ mode. Any rules nested in a _None_ block are negated, so a contains becomes a does not contain. This is a bit convoluted, I know, but Apple’s frameworks allow for little extensibility in this regard. (See also the [Glyphs Handbook](https://cdn2.glyphsapp.com/media/pages/learn/f84e457b88-1639830290/glyphs-3.0.4-handbook.pdf#page92) on Smart Filters, page 92 and especially 94.) **Begins with** and **ends with** are not available for lists (such as tags) with the rule editor that Apple provides, but maybe we can work around that.

2: Offering a menu might be possible. Regarding hot-linking for renaming: that is something that Guten Tag might do, but if you rename tags manually (i.e. not using the dedicated Rename feature of Guten Tag), than that would register as deleting a tag and creating a new tag, since that is what you would habe to do to rename a tag manually. Such manual renaming would not be recognized by the smart filters as a rename.

3: Control-click or richt-click a glyph in Font View and you will see all tags of the font in the Tags menu (see [page 84 of the Glyphs Handbook](https://cdn2.glyphsapp.com/media/pages/learn/f84e457b88-1639830290/glyphs-3.0.4-handbook.pdf#page84) for details). A better overview of all tags in a font is in the works, but I cannot give you a timeline for that.

**Comment by gorjious** [comment]
1. Convoluted but works perfectly! Looks like it gets boiled down into a `Custom` filter `NOT tags CONTAINS "name_of_tag"`. The other options are probably less important but I guess a lot comes down to tag organization. 

Thanks for the info! Great plugin and looking forward to using it more.
